"""empty message

Revision ID: 023359dd6d0a
Revises: 026028aef03e
Create Date: 2024-05-29 14:38:32.052737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '023359dd6d0a'
down_revision = '026028aef03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profesional', schema=None) as batch_op:
        batch_op.drop_column('servicio_pasteleria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profesional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_pasteleria', postgresql.ENUM('clase_de_pasteleria', 'desayuno', 'merienda', name='servicio_pasteleria'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
