"""empty message

Revision ID: 826f7a4872c0
Revises: 8f91f2831447
Create Date: 2024-05-23 17:54:35.968040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826f7a4872c0'
down_revision = '8f91f2831447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
