"""empty message

Revision ID: 8f91f2831447
Revises: 4909349f06ba
Create Date: 2024-05-23 11:51:39.854029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f91f2831447'
down_revision = '4909349f06ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios_contratados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=30), nullable=True),
    sa.Column('nombre_profesional', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('texto', sa.String(length=400), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('nombre_usuario', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.String(length=12), nullable=False))
        batch_op.add_column(sa.Column('dni', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('localización', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('foto_de_perfil', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('info_adicional', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_pica_pica', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_clase_cocina', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_clase_pasteleria', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_clase_corte_jamon', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_comida_trabajo', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_degustacion', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_batchcooking', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_corte_jamon', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_cata_vinos', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_maridaje', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_barman', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('servicio_clase_cockteleria', sa.String(length=300), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['telefono'])
        batch_op.create_unique_constraint(None, ['dni'])
        batch_op.create_unique_constraint(None, ['foto_de_perfil'])
        batch_op.create_unique_constraint(None, ['nombre_usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('servicio_clase_cockteleria')
        batch_op.drop_column('servicio_barman')
        batch_op.drop_column('servicio_maridaje')
        batch_op.drop_column('servicio_cata_vinos')
        batch_op.drop_column('servicio_corte_jamon')
        batch_op.drop_column('servicio_batchcooking')
        batch_op.drop_column('servicio_degustacion')
        batch_op.drop_column('servicio_comida_trabajo')
        batch_op.drop_column('servicio_clase_corte_jamon')
        batch_op.drop_column('servicio_clase_pasteleria')
        batch_op.drop_column('servicio_clase_cocina')
        batch_op.drop_column('servicio_pica_pica')
        batch_op.drop_column('info_adicional')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('foto_de_perfil')
        batch_op.drop_column('direccion')
        batch_op.drop_column('localización')
        batch_op.drop_column('dni')
        batch_op.drop_column('telefono')
        batch_op.drop_column('nombre_usuario')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    op.drop_table('chat')
    op.drop_table('servicios_contratados')
    # ### end Alembic commands ###
