"""empty message

Revision ID: a98fa96b3628
Revises: 
Create Date: 2024-06-08 12:01:53.214123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98fa96b3628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('apellidos', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=True),
    sa.Column('localizacion', sa.Enum('madrid', 'barcelona', 'valencia', name='localizacion'), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('foto_de_perfil', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('info_adicional', sa.String(length=300), nullable=True),
    sa.Column('tipo_de_profesional', sa.Enum('chef', 'barman', 'cortador de jamon', 'sumiller', 'pastelero', name='tipo_de_profesional'), nullable=True),
    sa.Column('tipo_de_cocina_especialidad', sa.Enum('cocina española', 'cocina peruana', 'cocina griega', 'cocina americana', 'cocina italiana', 'cocina argentina', 'cocina tailandesa', 'cocina mexicana', 'cocina creativa', 'cocina japonesa', 'cocina vegana', name='tipo_de_cocina'), nullable=True),
    sa.Column('tipo_servicio_chef_pica_pica', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_chef_taller_de_cocina', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_chef_comida_de_trabajo', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_chef_servicio_degustacion', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_chef_comida_informal', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_chef_batchcooking', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_jamonero_corte', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_jamonero_clase_corte', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_sumiller_maridaje', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_sumiller_cata', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_pastelero_clase', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_pastelero_desayuno', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_pastelero_merienda', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_barman_barra', sa.Text(), nullable=True),
    sa.Column('tipo_servicio_barman_clase', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('foto_de_perfil'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('apellidos', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=True),
    sa.Column('localizacion', sa.String(length=20), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('foto_de_perfil', sa.String(), nullable=True),
    sa.Column('tipo_de_dieta', sa.Enum('Vegetariano', 'Vegano', 'Omnivoro', name='tipo_de_dieta'), nullable=True),
    sa.Column('alergias', sa.String(length=50), nullable=True),
    sa.Column('reset_token', sa.String(length=120), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('foto_de_perfil'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('coment_text', sa.String(length=800), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['Profesional.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['Profesional.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios_contratados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('numero_personas', sa.Integer(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('servicio_profesional', sa.String(), nullable=True),
    sa.Column('tipo_evento', sa.String(), nullable=True),
    sa.Column('localizacion', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('servicio_incluye', sa.String(), nullable=True),
    sa.Column('costo_servicio', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('fecha_contratacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['Profesional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicios_contratados')
    op.drop_table('favoritos')
    op.drop_table('conversacion')
    op.drop_table('User')
    op.drop_table('Profesional')
    # ### end Alembic commands ###
