"""empty message

Revision ID: afa9f52187c4
Revises: 
Create Date: 2024-06-01 11:11:19.399219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa9f52187c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profesional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('apellidos', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=True),
    sa.Column('localizacion', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('foto_de_perfil', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('info_adicional', sa.String(length=300), nullable=True),
    sa.Column('tipo_de_profesional', sa.Enum('Chef', 'Barman', 'Cortador de jamon', 'Sumiller', 'Pastelero', name='tipo_de_profesional'), nullable=True),
    sa.Column('tipo_de_cocina', sa.Enum('cocina española', 'cocina peruana', 'cocina griega', 'cocina americana', 'cocina italiana', 'cocina argentina', 'cocina tailandesa', 'cocina mexicana', 'cocina creativa', 'cocina japonesa', 'cocina vegana', name='tipo_de_cocina'), nullable=True),
    sa.Column('tipo_servicio_chef', sa.Enum('Pica-pica', 'Taller de cocina', 'Comida trabajo', 'Servicio degustación', 'Comida informal', 'Batchcooking', name='tipo_servicio_chef'), nullable=True),
    sa.Column('tipo_servicio_jamonero', sa.Enum('Corte de jamón', 'Clase de corte de jamón', name='tipo_servicio_jamonero'), nullable=True),
    sa.Column('tipo_servicio_sumiller', sa.Enum('Cata de vinos', 'Maridaje', name='tipo_servicio_sumiller'), nullable=True),
    sa.Column('tipo_servicio_pastelero', sa.Enum('Clase de pasteleria', 'Servicio de desayunos', 'Servicio de meriendas', name='tipo_servicio_pastelero'), nullable=True),
    sa.Column('tipo_servicio_barman', sa.Enum('Clase de cocteleria', 'Servicio de barra', name='tipo_servicio_barman'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('foto_de_perfil'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('apellidos', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=True),
    sa.Column('localizacion', sa.String(length=20), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('foto_de_perfil', sa.String(), nullable=True),
    sa.Column('tipo_de_dieta', sa.Enum('Vegetariano', 'Vegano', 'Omnivoro', name='tipo_de_dieta'), nullable=True),
    sa.Column('alergias', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('foto_de_perfil'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('coment_text', sa.String(length=800), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['Profesional.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['Profesional.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios_contratados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('pax', sa.Integer(), nullable=True),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['Profesional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicios_contratados')
    op.drop_table('favoritos')
    op.drop_table('conversacion')
    op.drop_table('User')
    op.drop_table('Profesional')
    # ### end Alembic commands ###
