"""empty message

Revision ID: f0ae54306a64
Revises: 31f77b379742
Create Date: 2024-06-13 14:28:26.962087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ae54306a64'
down_revision = '31f77b379742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profesional', schema=None) as batch_op:
        batch_op.drop_column('tipo_servicio_chef')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Profesional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_servicio_chef', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
